Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,79 +1,117 @@
-name: Build OPLUS
+name: Build Kernel
+
 on:
   workflow_dispatch:
+
 jobs:
   build:
-    runs-on: ubuntu-latest
+    name: Build Surya Kernel
+    runs-on: buildjet-32vcpu-ubuntu-2204-arm
+
+    env:
+      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
+
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v4
+      - name: Checkout Kernel Source
+        uses: actions/checkout@v3
+
+      - name: Prepare timezone 
+        run: |
+          echo "BUILD_TIME=$(TZ=Asia/Jakarta date '+%d%m%Y-%H%M')" >> $GITHUB_ENV
+          sudo rm /etc/localtime
+          sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
+
+      - name: Set Up Dependencies
+        run: |
+          sudo apt update -y
+          sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 -y
+          sudo aptitude install libssl-dev -y
+          sudo apt install device-tree-compiler -y
+
+      - name: Run SukiSU Kernel Setup
+        run: |
+          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
+
+      - name: Clone ZyC Clang
+        run: |
+          mkdir RvClang
+          curl -LO https://github.com/Rv-Project/RvClang/releases/download/20.1.0/RvClang-20.1.0-bolt-pgo-full_lto.tar.gz
+          tar -C RvClang/ -xf rvclang.tar.gz
+
+      - name: Set Environment Variables
+        run: |
+          echo "KERNEL_DEFCONFIG=surya_defconfig" >> $GITHUB_ENV
+          echo "TOOLCHAIN=$(pwd)/RvClang" >> $GITHUB_ENV
+          echo "PATH=$(pwd)/RvClang/bin:$PATH" >> $GITHUB_ENV
+          echo "BUILD_USER=mahirooo" >> $GITHUB_ENV
+          echo "BUILD_HOST=android-build" >> $GITHUB_ENV
+          echo "BUILD_TIME=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV
+
+      - name: Send Telegram Notification - Build Started
+        run: |
+             CLANG_VER=$(./RvClang/bin/clang --version | head -n 1)
+             curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage \
+             -d chat_id=${TELEGRAM_CHAT_ID} \
+             -d text="🚀 *Build Dimulai!* | *Clang*: ${CLANG_VER}" \
+             -d parse_mode=Markdown
       
-    - name: Prepare timezone 
-      run: |
-            echo "BUILD_TIME=$(TZ=Asia/Jakarta date "+%d%m%Y-%H%M")" >> $GITHUB_ENV
-            sudo rm /etc/localtime
-            sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
-        
-    - name: Install Dependencies
-      run: |
-            sudo apt update -y
-            sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 -y
-            sudo aptitude install libssl-dev -y
-            sudo apt install device-tree-compiler -y
-        
-    - name: Fetch Toolchains 
-      run: |
-            mkdir clang && curl  https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -RLO && tar -C clang/ -xf clang-*.tar.gz
-            git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 gcc64
-            git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 gcc32
-                                    
-    - name: Fetch SukiSU
-      run: |
-            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
+      - name: Set Build Start Time
+        run: echo "BUILD_START=$(date +%s)" >> $GITHUB_ENV
 
-    - name: Clean previous build
-      run: |
-           make clean && make mrproper
+      - name: Make Defconfig
+        run: |
+          make O=out ARCH=arm64 ${KERNEL_DEFCONFIG}
 
-    - name: Build
-      run: |
-            export ARCH=arm64
-            export PATH="${PWD}/clang/bin:${PWD}gcc64/bin:${PWD}gcc32/bin:${PATH}"
-            export KBUILD_BUILD_USER=mahirooo
-            export KBUILD_BUILD_HOST=android-build
-            export KBUILD_COMPILER_STRING="${PWD}/clang"           
-            export LD=ld.lld
-            export AS=llvm-as
-            export AR=llvm-ar
-            export NM=llvm-nm
-            export OBJCOPY=llvm-objcopy
-            export OBJDUMP=llvm-objdump
-            export STRIP=llvm-strip
-            export CROSS_COMPILE=aarch64-linux-gnu-
-            export CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
-            export LLVM=1
-            export LLVM_IAS=1
-            export DTC_EXT=dtc
-            make O=out surya_defconfig 
-            make -j$(nproc --all) O=out CC=clang                   
-            mv out/.config out/surya_defconfig.txt
-           
-    - name: Upload defconfig 
-      uses: actions/upload-artifact@v4
-      with:
-        name: defconfig-${{ env.BUILD_TIME }}
-        path: out/surya_defconfig.txt
+      - name: Build Kernel
+        run: |
+          make -j$(nproc) O=out \
+            ARCH=arm64 \
+            LD=ld.lld \
+            AS=llvm-as \
+            AR=llvm-ar \
+            NM=llvm-nm \
+            OBJCOPY=llvm-objcopy \
+            OBJDUMP=llvm-objdump \
+            STRIP=llvm-strip \
+            CROSS_COMPILE=aarch64-linux-gnu- \
+            CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
+            CLANG_TRIPLE=aarch64-linux-gnu- \
+            LLVM=1 \
+            LLVM_IAS=1 \
+            DTC_EXT=dtc \
+            KBUILD_COMPILER_STRING="${PWD}/clang" \
+            KBUILD_BUILD_USER=${BUILD_USER} \
+            KBUILD_BUILD_HOST=${BUILD_HOST} 2>&1 | tee log.txt
+        continue-on-error: true
 
-    - name: Fetch Anykernel3
-      run: |
-            git clone --depth=1 https://github.com/rinnsakaguchi/AnyKernel3.git -b FSociety AnyKernel3
-            cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
-            cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
-            cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img
-                    
-    - name: Upload Kernel
-      uses: actions/upload-artifact@v4
-      with:
-        name: Anykernel3-surya-${{ env.BUILD_TIME }}
-        path: AnyKernel3/*
-        
+      - name: Send Telegram Notification - Build Failed (if failed)
+        if: failure()
+        run: |
+          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument \
+            -F chat_id=${TELEGRAM_CHAT_ID} \
+            -F document=@log.txt \
+            -F caption="❌ Build kernel *gagal*! Berikut log-nya 🧾." \
+            -F parse_mode=Markdown
+
+      - name: Check Kernel Output Files
+        run: |
+          [[ -f out/arch/arm64/boot/Image.gz ]] || { echo "❌ Missing Image.gz"; exit 1; }
+          [[ -f out/arch/arm64/boot/dtbo.img ]]  || { echo "❌ Missing dtbo.img"; exit 1; }
+          [[ -f out/arch/arm64/boot/dtb.img ]]   || { echo "❌ Missing dtb.img"; exit 1; }
+
+      - name: Fetch AnyKernel3 and Package
+        run: |
+          git clone --depth=1 https://github.com/rinnsakaguchi/AnyKernel3.git -b FSociety AnyKernel3
+          cp out/arch/arm64/boot/Image.gz AnyKernel3/Image.gz
+          cp out/arch/arm64/boot/dtbo.img AnyKernel3/dtbo.img
+          cp out/arch/arm64/boot/dtb.img AnyKernel3/dtb.img
+          cd AnyKernel3
+          zip -r9 ../Surya-Kernel-${{ env.BUILD_TIME }}.zip ./*
+
+      - name: Send Build to Telegram
+        run: |
+          curl -F document=@Surya-Kernel-${{ env.BUILD_TIME }}.zip \
+          -F caption="Build Success With RvClang" \
+          -F parse_mode=Markdown \
+          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}"
